### ISSUE TITLE
Bots can't finish Boots of Bearing

### ISSUE THREAD

**Issue by am3692** [ryndrb/dota2bot#33] opened 2024-05-22 05:53 UTC
In this game, Clockwork sold Tranquil Boots while trying to buy Boots of Bearing
![image](https://github.com/ryndrb/dota2bot/assets/4267326/22cb60a5-6793-465a-92a0-b6d512b096b2)
![image](https://github.com/ryndrb/dota2bot/assets/4267326/3091ccc3-4c4c-4b7e-9b0b-8af3b86e3803)
![image](https://github.com/ryndrb/dota2bot/assets/4267326/d2599ef6-6fba-4d43-b2df-7e7e5d6db677)
![image](https://github.com/ryndrb/dota2bot/assets/4267326/935e1ff0-ca5f-4a52-8b5d-1a028b9493a1)

**Comment by forest0xia** [comment] 2024-06-28 09:12
This is a problem because that bot kept supporting items in backpack and when it purchases the new components, the new components got dropped on the ground. Which is a stupid issue or feature by Valve that can happen to any human players as well. But human is intelligent enough to drop and pick up with different combinations to assemble the items, which is hard for bots to do. Because some components items may in courier. 

This is a systematic problem by design, and bots need to know what to drop and repick items on ground in some specific order.

**Comment by forest0xia** [comment] 2024-07-06 00:17
The reference you added won't fix this problem. To fix this problem you need to have a good strategy for the bots to pick up items on the ground. But it's hard because when this issue happens, the bot most likely does not have any empty slots to pick items. So they either need to know what to drop to ground to pick up the component items on ground and finish the item building, or having courier to help picking things up and combine components, note currently we do not have sufficient APIs to do this easily.

You can reproduce this easily by assigning the bot with complex items that requires a lot of components. And give bots 50000 gold so they will try to buy the items quickly, which you will see this can happen again pretty frequently.

**Comment by ryndrb** [comment] 2024-08-18 16:06
Tracked in Issues #8 .

**Closed by ryndrb** 2024-08-18 16:06 UTC
Labels: bug
